id: P82F3B8FF
initial_creation_type: input
source_metadata:
  title: 'BA: Daśabhūmikasūtra'
  language: zh
  volumes:
    3cc7eacf9bcc4c0ea42032db3ef4686b:
      title: .txt
      base_file: .txt.txt
      work_id: WBD252419
  chapter_to_tile: {}
created_at: '2022-03-01T21:20:55.577085'
last_modified_at: '2022-03-01T21:20:55.577093'
